name: Rust CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Check compilation
      run: cargo check

    - name: Run unit tests
      run: cargo test

    - name: Enforce Pedantic Clippy
      run: cargo clippy -- -D warnings -W clippy::pedantic